version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel-mix
    versions:
    - 5.0.9
    - 6.0.11
    - 6.0.13
    - 6.0.16
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
